export const SCREENS = {
  Index: 'Index',
  Recharge: 'Recharge',
  Cart: 'Cart',
  Me: 'Me',
  Category: 'Category',
  Main: 'Main',
  ProductDetail: 'ProductDetail',
  Login: 'Login',
  RegisterStepOne: 'RegisterStepOne',
  RegisterStepTwo: 'RegisterStepTwo',
  SearchResult: 'SearchResult',
  MyCollection: 'MyCollection',
  Settings: 'Settings',
  Language: 'Language',
};
